use_frameworks!

target 'CollectionModel_Example' do
  pod 'CollectionModelCore', :path => '../'
  pod 'CollectionModelAnimation', :path => '../'

  target 'CollectionModel_Tests' do
    inherit! :search_paths

    
  end
end
